# autogenerated by txs
\AmS#S
\AmSTeX#S
\BibTeX#S
\LaTeX#S
\LaTeXe#S
\SliTeX#S
\TeX#S
\cmrLaTeX#S
\cmrTeX#S
\pLaTeX#S
\pLaTeXe#S
\pTeX#S
\pdfstringdefPreHook#S
\pncLaTeX#S
\pncTeX#S
\pplLaTeX#S
\pplTeX#S
\ptmLaTeX#S
\ptmTeX#S
\sfLaTeX#S
\sfTeX#S
\ugmLaTeX#S
\ugmTeX#S
\upLaTeX#S
\upLaTeXe#S
\upTeX#S
\BibTeX #S
\SliTeX #S
\TeX #S
