# autogenerated by txs
#include:expl3
#include:l3keys2e
#include:luatexja
#include:luatexja-fontspec
\ebdefault#S
\ebseries#S
\gtebfamily#S
\ltdefault#S
\ltjnewpreset#S
\ltseries#S
\mgfamily#S
\rubyfamily#S
